require("./AdminLTEScss/AdminLTE.scss");
require("./font-awesome.min.css");
require("./comment.css");
require("./attachment.scss");
require("./board.scss");
require("./trumbowyg.scss");
require("datatables.net-bs4/css/dataTables.bootstrap4.css");
require("datatables.net-colreorder-bs4/css/colReorder.bootstrap4.css");
require("datatables.net-select-bs4/css/select.bootstrap4.css");
require("select2/dist/css/select2.css");
import "bootstrap"
import "./adminlte.min.js";
import "./data/configuration";
import "./ui/image";
import "./ui/loader";
import "./ui/alert";
import "./crud-operations";
import "./ui/modal";
import "./ui/form";
import "./data/client";
import "./data/localstorage"
import "./datatable";
import "./components/entity.component";
import "./components/employee.component";
import "./components/comment.component";
import "./components/position.component";
import "./components/jobpost.component";
import "./components/inventory.component";
import "./components/chart.component";
import "./components/attachment.component";
import "./components/news.component";
import "./components/history.component";
import "./ui/tag";
import "./components/candidate.component";
import "./components/social-media.component";
import "./components/health.component";
import "./ui/board";
import "./ui/edit";
import "./initRichTextEditor";
import "../../scripts/jquery.validate";
import "../../scripts/jquery.validate.unobtrusive";
import "../../scripts/jquery.unobtrusive-ajax";
import "datatables.net-bs4";
import "datatables.net-buttons-bs4";
import "datatables.net-buttons/js/buttons.flash.js";
import "datatables.net-buttons/js/buttons.html5.js";
import "datatables.net-buttons/js/buttons.print.js";
import "datatables.net-responsive-bs4";
import "datatables.net-select";
import "jszip";
import "select2";
import "clipboard";
//import "turndown";
import "./data/copy";
//import "jquery-ui";
window.$ = window.jQuery = require("jquery");
//import "jquery";
//import "./components/search.component";
